### ISSUE TITLE
关于这句话的翻译:".如果查找到的值是一个描述器, Python就会调用描述器的方法来重写默认的控制行为"

### ISSUE THREAD

**Issue by usernameisnull** [MrKiven/PyZh#18]
原文是：
“If the looked-up value is an object defining one of the descriptor methods, then Python may override the default behavior and invoke the descriptor method instead”
感觉翻译成下面是不是更贴近愿意些：
如果找到的值是一个有描述器方法的对象。。。

**Comment by MrKiven** [comment]
I'm busying now. patch is welcome!
